### ISSUE TITLE
All sensors disabled

### ISSUE THREAD

**Issue by che-wf** [tim-hellhake/netatmo-weather-adapter#4]
Recently, I have had an issue where all of my sensors are disabled in my Gateway. I tried checking authentication. That's still valid. I tried uninstalling the addon and reinstalling. That didn't do the trick either. So, I took a look at the logs and this is what I'm seeing:

```sh
2019-05-02 01:06:39.565 ERROR  : netatmo-weather: /home/pi/.mozilla-iot/addons/netatmo-weather-adapter/adapter.js:139
2019-05-02 01:06:39.566 ERROR  : netatmo-weather:             this.properties.set(dataType, new NetatmoProperty(this, dataType, props, netatmoDevice.dashboard_data[dataType]));
2019-05-02 01:06:39.568 ERROR  : netatmo-weather:
                     ^
2019-05-02 01:06:39.569 ERROR  : netatmo-weather:
2019-05-02 01:06:39.570 ERROR  : netatmo-weather: TypeError: Cannot read property 'Temperature' of undefined
2019-05-02 01:06:39.573 ERROR  : netatmo-weather:     at new WeatherStation (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/adapter.js:139:114)
2019-05-02 01:06:39.574 ERROR  : netatmo-weather:     at NetatmoWeatherAdapter.addDevice (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/adapter.js:235:28)
2019-05-02 01:06:39.576 ERROR  : netatmo-weather:     at NetatmoWeatherAdapter.addDevice (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/adapter.js:244:22)
2019-05-02 01:06:39.577 ERROR  : netatmo-weather:     at netatmo.getStationsData (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/adapter.js:299:26)
2019-05-02 01:06:39.579 ERROR  : netatmo-weather:     at netatmo.<anonymous> (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/node_modules/netatmo/netatmo.js:227:14)
2019-05-02 01:06:39.580 ERROR  : netatmo-weather:     at Request.self.callback (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/node_modules/request/request.js:185:22)
2019-05-02 01:06:39.582 ERROR  : netatmo-weather:     at emitTwo (events.js:126:13)
2019-05-02 01:06:39.584 ERROR  : netatmo-weather:     at Request.emit (events.js:214:7)
2019-05-02 01:06:39.585 ERROR  : netatmo-weather:     at Request.<anonymous> (/home/pi/.mozilla-iot/addons/netatmo-weather-adapter/node_modules/request/request.js:1161:10)
2019-05-02 01:06:39.586 ERROR  : netatmo-weather:     at emitOne (events.js:116:13)
2019-05-02 01:06:39.590 INFO   : Plugin: netatmo-weather-adapter died, code = 1 restarting...
```

The problem is that I haven't added any modules to my Netatmo station. However, I think the battery may have died on one. I'm guessing that may be the culprit. But I'm not sure why it would still be trying to set a property on a module that isn't being read. (I'm guessing that's what is happening.) Is my one module with the dead battery causing the failure of the plugin?

**Comment by freaktechnik** [comment]
It appears the API isn't including the temperature for the device, even though it's saying the device can measure the temperature. I'll add a guard against this crash in the next version.
